# Generated by Django 5.1.3 on 2024-11-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcard_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard',
        ),
    ]
