# Generated by Django 5.1.3 on 2024-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0023_alter_box_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsindexpage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
