# Generated by Django 5.1.3 on 2024-12-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0024_flashcardsindexpage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardsindexpage',
            name='subject',
        ),
        migrations.AddField(
            model_name='flashcardsindexpage',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
