# Generated by Django 5.1.3 on 2024-12-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0026_alter_flashcard_options_flashcard_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardsindexpage',
            name='prompt',
        ),
        migrations.AddField(
            model_name='flashcardsindexpage',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a brief description or introduction for this deck.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flashcardsindexpage',
            name='chatgpt_answer',
            field=models.TextField(blank=True, help_text='Use the following prompt: "Transform the content below into flashcards in the format Question::Answer (one per line, without enumeration), where the questions are based on the key concepts from the text, according to the guidelines of SuperMemo by Piotr Wozniak. The text and the flashcards must be kept in the same language in which the content was provided."', verbose_name='Paste here the answer from your favorite language model platform'),
        ),
    ]
