# Generated by Django 5.1.3 on 2024-12-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0027_remove_flashcardsindexpage_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpage',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='folderpage',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a brief description for this folder.', verbose_name='Description'),
        ),
    ]
