# Generated by Django 5.1.3 on 2024-11-24 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_delete_flashcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsindexpage',
            name='cloned_by',
            field=models.ForeignKey(blank=True, help_text='The user who cloned this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_flashcard_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
