# Generated by Django 5.1.3 on 2024-11-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_remove_flashcardsindexpage_cloned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsindexpage',
            name='chatgpt_answer',
            field=models.TextField(blank=True, help_text="Paste the array of flashcards in the format: 'question::answer' (one per line)."),
        ),
    ]
