# Generated by Django 5.1.3 on 2024-11-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_flashcard_delete_flashcardpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='flashcards_media/'),
        ),
    ]
