# Generated by Django 5.1.3 on 2024-11-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_flashcard_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='media',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='answer_media',
            field=models.FileField(blank=True, null=True, upload_to='flashcards_media/answers/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question_media',
            field=models.FileField(blank=True, null=True, upload_to='flashcards_media/questions/'),
        ),
    ]
