# Generated by Django 5.1.3 on 2024-11-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_alter_flashcard_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='media',
        ),
    ]
