# Generated by Django 5.1.3 on 2024-11-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_remove_flashcard_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='flashcards_media/'),
        ),
    ]
