# Generated by Django 5.1.3 on 2024-12-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_alter_flashcard_options_flashcard_media'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, help_text='Descrição da pasta', null=True)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, help_text='Descrição do deck', null=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='flashcards.folder')),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
            },
            bases=('wagtailcore.page',),
        ),
    ]
