# Generated by Django 5.1.3 on 2024-12-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_folder_deck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcardsindexpage',
            options={'verbose_name': 'Deck', 'verbose_name_plural': 'Decks'},
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
