# Generated by Django 5.1.3 on 2024-12-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0019_box'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Box', 'verbose_name_plural': 'Boxes'},
        ),
        migrations.RemoveField(
            model_name='box',
            name='intro',
        ),
    ]
