# Generated by Django 5.1.3 on 2024-12-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0020_alter_box_options_remove_box_intro'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Root',
                'verbose_name_plural': 'Root',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Folders', 'verbose_name_plural': 'Folders'},
        ),
    ]
