# Generated by Django 5.1.3 on 2024-12-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0025_remove_flashcardsindexpage_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
